export const model = {
  smartphone: [
    "Apple",
    "Asus",
    "Google",
    "Huawei Honor",
    "Huawei",
    "LG",
    "Motorola",
    "Nothing Phone (1)",
    "OnePlus",
    "Oppo",
    "Poco",
    "Realme",
    "Samsung",
    "Vivo",
    "Xiaomi Redmi",
    "iQOO",
    "Nokia",
    "Blackberry",
    "10. or G",
    "Infinix",
    "Lenovo",
    "LG",
    "Micromax",
    "Tecno",
  ],
  laptop: [
    "APPLE",
    "ACER",
    "ALIENWARE",
    "MSI",
    "DELL",
    "LG",
    "HUAWEI",
    "LENOVO",
    "HP",
    "RAZER",
    "MICROSOFT",
    "SAMSUNG",
    "SONY",
    "TOSHIBA",
    "XIAOMI",
  ],
};

export const versionname = {
  smartphone: {
    apple: [
      "Apple iPhone 14",
      "Apple iPhone 14 Pro ",
      "Apple iPhone 14 Pro Max ",
      "Apple iPhone 14 Plus",
      "Apple iPhone 13 ",
      "Apple iPhone 13 Pro",
      "Apple iPhone 13 Pro Max",
      "Apple iPhone 13 Mini",
      "Apple iPhone 12",
      "Apple iPhone 12 Mini",
      "Apple iPhone 12 Pro ",
      "Apple iPhone 12 Pro Max",
      "Apple iPhone 11",
      "Apple iPhone 11 Pro ",
      "Apple iPhone 11 Pro Max",
      "Apple iPhone XS",
      "Apple iPhone XS Max ",
      "Apple iPhone X ",
      "Apple iPhone XR ",
      "Apple iPhone SE 2020",
      "Apple iPhone 8",
      "Apple iPhone 8 Plus ",
      "Apple iPhone 7",
      "Apple iPhone 7 Plus ",
      "Apple iPhone 6 ",
      "Apple iPhone 6 Plus ",
      "Apple iPhone 6S ",
      "Apple iPhone 6S Plus ",
      "Apple iPhone 5",
      "Apple iPhone 5C ",
      "Apple iPhone 5S",
      "Apple iPhone SE",
    ],
    asus: [
      "Asus Rog 2",
      "Asus Rog 3",
      "Asus Rog 5",
      "Asus Zenfone Max Pro M1 ",
      "Asus Zenfone Max Pro M2 ",
      "Asus Zenfone Max M2 (No Sides)",
      "Asus Zenfone 5Z",
      "Asus Zenfone 6",
      "Asus Zenfone 6Z",
      "Asus Zenfone 8Z (No Sides)",
    ],
    google: [
      "Google Pixel 2",
      "Google Pixel 2 Xl ",
      "Google Pixel 3 ",
      "Google Pixel 3A ",
      "Google Pixel 3Xl",
      "Google Pixel 3A XL",
      "Google Pixel 4",
      "Google Pixel 4Xl",
      "Google Pixel 4A",
      "Google Pixel 4A 5G",
      "Google Pixel 5",
      "Google Pixel 5A",
      "Google Pixel 6",
      "Google Pixel 6A",
      "Google Pixel 6 Pro",
      "Google Pixel 7 (No Sides)",
      "Google Pixel 7 Pro (No Sides)",
    ],
    honor: ["LG G8X ThinQ", "LG Wign"],
    "huawei honor": ["LG G8X ThinQ", "LG Wign"],
    motorola: ["LG G8X ThinQ", "LG Wign"],
    "nothing phone (1)": ["Nothing Phone (1)"],
    oneplus: [
      "OnePlus 5",
      "OnePlus 5T",
      "OnePlus 6",
      "OnePlus 6T",
      "OnePlus 7",
      "OnePlus 7T",
      "OnePlus 7 Pro",
      "OnePlus Nord",
      "OnePlus Nord 2",
      "OnePlus 8T",
      "OnePlus 8",
      "OnePlus 8 Pro",
      "OnePlus X",
      "OnePlus 9",
      "OnePlus 9 Pro",
      "OnePlus 9R",
      "OnePlus 9RT 5G",
      "OnePlus Nord CE 2 5G",
      "OnePlus Nord CE 5G ",
      "OnePlus Nord CE 2 LITE ",
      "OnePlus Nord N200",
      "OnePlus Nord N10",
      "OnePlus Nord 2T 5G ",
      "OnePlus 10 pro (5G)",
      "OnePlus Nord N20 SE ",
      "OnePlus 10R (5G) ",
      "OnePlus 10T",
    ],
    oppo: ["LG G8X ThinQ", "LG Wign"],
    poco: [
      "Poco F1",
      "Poco F2 Pro",
      "Poco F3",
      "Poco F3 GT 5G ",
      "Poco F4 ",
      "Poco F4 GT",
      "Poco X2",
      "Poco X3",
      "Poco X3 NFC",
      "Poco X3 GT ",
      "Poco X3 Pro",
      "Poco X4 Pro (No Sides)",
      "Poco M2",
      "Poco M2 Pro",
      "Poco C3",
      "Poco M3 (No Sides)",
      "Poco C31",
      "Poco M3 Pro 5G",
      "Poco M4 5G (No Sides) ",
      "Poco M4 Pro 5G",
    ],
    realme: ["LG G8X ThinQ", "LG Wign"],
    lenovo: [
      "Lenovo K3 Note",
      "Lenovo K4 Note ",
      "Lenovo K5 Note ",
      "Lenovo K6 Note",
      "Lenovo K6 Power",
      "Lenovo K8 ",
      "Lenovo K8 Note",
      "Lenovo K8 Plus",
      "Lenovo Vibe K6 Power",
      "Lenovo Vibe P1",
      "Lenovo Zuk Z1 ",
      "Lenovo Zuk Z2",
      "Lenovo Zuk Z2 Lite",
      "Lenovo Zuk Z2 Plus",
      "Lenovo Zuk Z2 Pro",
    ],
    lg: [
      "Lg G5",
      "Lg G6",
      "Lg G7",
      "Lg G7+",
      "Lg G8X Thinq",
      "Lg K10",
      "Lg K10 2017",
      "Lg K7",
      "Lg K9",
      "Lg K90",
      "Lg Pro Lite",
      "Lg Q6",
      "Lg Q7",
      "Lg Q8",
      "Lg Stylus 2",
      "Lg Stylus 4",
      "Lg V20",
      "Lg V30",
      "Lg V30+",
      "Lg V40 Thinq",
      "Lg Velvet",
      "Lg W30",
      "Lg X Power",
      "Lg Wing",
      "Lg Q Stylus Plus",
    ],
    samsung: [
      "Samsung Galaxy A03 Core ",
      "Samsung Galaxy A04S ",
      "Samsung Galaxy A6 Plus 2018",
      "Samsung Galaxy A8 Plus ",
      "Samsung Galaxy A8 Star",
      "Samsung Galaxy A9 ",
      "Samsung Galaxy A9 2016",
      "Samsung Galaxy A9 2018",
      "Samsung Galaxy A9 Pro",
      "Samsung Galaxy A10",
      "Samsung Galaxy A10S",
      "Samsung Galaxy A12",
      "Samsung Galaxy A20E (No Sides)",
      "Samsung Galaxy A20",
      "Samsung Galaxy A21 (No Sides)",
      "Samsung Galaxy A20S",
      "Samsung Galaxy A33 (5G)",
      "Samsung Galaxy A30",
      "Samsung Galaxy A31",
      "Samsung Galaxy A32",
      "Samsung Galaxy A30s",
      "Samsung Galaxy A21S",
      "Samsung Galaxy A22 ",
      "Samsung Galaxy A33 ",
      "Samsung Galaxy A22 5G",
      "Samsung Galaxy A23",
      "Samsung Galaxy A13 5G ",
      "Samsung Galaxy A42",
      "Samsung Galaxy A41",
      "Samsung Galaxy A50S",
      "Samsung Galaxy A50",
      "Samsung Galaxy A50S",
      "Samsung Galaxy A51 ",
      "Samsung Galaxy A52",
      "Samsung Galaxy A52s 5G",
      "Samsung Galaxy A53 5G",
      "Samsung Galaxy A60 ",
      "Samsung Galaxy A70 ",
      "Samsung Galaxy A70S ",
      "Samsung Galaxy A71 ",
      "Samsung Galaxy A72",
      "Samsung Galaxy A73",
      "Samsung Galaxy A80",
      "Samsung Galaxy Alpha",
      "Samsung Galaxy C7 ",
      "Samsung Galaxy C7 Pro",
      "Samsung Galaxy C9",
      "Samsung Galaxy C9 Pro ",
      "Samsung Galaxy Core 2",
      "Samsung Galaxy E5",
      "Samsung Galaxy E7 ",
      "Samsung Galaxy F12",
      "Samsung Galaxy F22 (No Sides)",
      "Samsung Galaxy F23",
      "Samsung Galaxy F41 ",
      "Samsung Galaxy F42 5G",
      "Samsung Galaxy F62",
      "Samsung Galaxy J7 Next",
      "Samsung Galaxy J7 Prime",
      "Samsung Galaxy J7 Pro",
      "Samsung Galaxy J8 2018",
      "Samsung Galaxy M02",
      "Samsung Galaxy M02S",
      "Samsung Galaxy M10",
      "Samsung Galaxy M11",
      "Samsung Galaxy M12",
      "Samsung Galaxy M13 5G",
      "Samsung Galaxy M20",
      "Samsung Galaxy M21",
      "Samsung Galaxy M21 2021",
      "Samsung Galaxy M22 (No Sides)",
      "Samsung Galaxy M30",
      "Samsung Galaxy M30s",
      "Samsung Galaxy M31",
      "Samsung Galaxy M32",
      "Samsung Galaxy M32 5G",
      "Samsung Galaxy M33 5G",
      "Samsung Galaxy M40",
      "Samsung Galaxy M42",
      "Samsung Galaxy M51",
      "Samsung Galaxy M52 5G",
      "Samsung Galaxy M53 5G",
      "Samsung Galaxy M62 ",
      "Samsung Galaxy Note 9",
      "Samsung Galaxy Note 9 Pro",
      "Samsung Galaxy Note Edge",
      "Samsung Galaxy Note 10 ",
      "Samsung Galaxy Note 10 Lite",
      "Samsung Galaxy Note 10 Plus",
      "Samsung Galaxy Note 20",
      "Samsung Galaxy Note 20 Ultra ",
      "Samsung Galaxy On 6 ",
      "Samsung Galaxy On 8",
      "Samsung Galaxy On Max",
      "Samsung Galaxy On Next",
      "Samsung Galaxy S10 ",
      "Samsung Galaxy S10 Lite ",
      "Samsung Galaxy S10 Plus",
      "Samsung Galaxy S10E",
      "Samsung Galaxy S20",
      "Samsung Galaxy S20 FE",
      "Samsung Galaxy S20 Plus",
      "Samsung Galaxy S20 Ultra",
      "Samsung Galaxy S21",
      "Samsung Galaxy S21 Plus",
      "Samsung Galaxy S21 Ultra ",
      "Samsung Galaxy S21 FE 5G",
      "Samsung Galaxy S22",
      "Samsung Galaxy S22 Plus ",
      "Samsung Galaxy S22 Ultra",
      "Samsung Galaxy Z2",
      "Samsung Galaxy Z3",
      "Samsung Galaxy Z Flip",
      "Samsung Galaxy Z Flip 3",
      "Samsung Galaxy Z Flip 4 ",
      "Samsung Galaxy Fold",
      "Samsung Galaxy Z Fold 2",
      "Samsung Galaxy Z Fold 3",
      "Samsung Galaxy Z Fold 4",
    ],
    infinix: [
      "Infinix 10 Play",
      "Infinix Hot 10 (No Sides)",
      "Infinix Hot 10S ",
      "Infinix Hot 11",
      "Infinix Hot 11S",
      "Infinix Hot 4",
      "Infinix Hot 4 Pro",
      "Infinix Hot 6 (No Sides)",
      "Infinix Hot 7 (No Sides)",
      "Infinix Hot 8 (No Sides)",
      "Infinix Hot 9 (No Sides)",
      "Infinix Hot 9 Pro ",
      "Infinix Hot 9 Pro (No Sides)",
      "Infinix Note 10",
      "Infinix Note 11S",
      "Infinix Note 12",
      "Infinix Note 4 Pro",
      "Infinix Note 5",
      "Infinix Note 7",
      "Infinix Note 8",
      "Infinix Note 9",
      "Infinix Smart 5A ",
      "Infinix Zero 8i (No Sides)",
    ],
    vivo: ["LG G8X ThinQ", "LG Wign"],
    "xiaomi redmi": ["LG G8X ThinQ", "LG Wign"],
    iqoo: [
      "Vivo IQOO 3 (No Sides)",
      "Vivo IQOO Neo 3 (No Sides)",
      "Vivo IQOO Neo 6 (5G)",
      "Vivo IQOO Z3",
      "Vivo IQOO 7",
      "Vivo IQOO Z1X",
      "Vivo IQOO 7 Legend (No Sides)",
      "Vivo IQOO Z5",
      "Vivo IQOO Z6 5G",
      "Vivo IQOO Z6 Pro 5G",
      "Vivo IQOO Z6 (44W)",
      "Vivo IQOO Z6 Lite 5G",
      "Vivo IQOO 9 5G",
      "Vivo IQOO 9 SE 5G",
      "Vivo IQOO 9 Pro 5G",
      "Vivo IQOO 9T (No Sides)",
    ],
    "10. or g": ["10. or G (No Sides) ", "10. or G 2"],
    blackberry: ["Blackberry Passport", "Blackberry Priv", "Blackberry Z10"],
  },
  laptop: {
    apple: [
      "MacBook 12” (2015) A1534",
      "MacBook Air 11” (2011)",
      'MacBook Air 13" (2010-2017) A1466',
    ],
    acer: ["HP PAVILION 15-EC1054AX"],
    msi: ["HP PAVILION 15-EC1054AX"],
    dell: ["HP PAVILION 15-EC1054AX"],
    alienware: ["HP PAVILION 15-EC1054AX"],
    lenovo: ["HP PAVILION 15-EC1054AX"],
    razer: ["HP PAVILION 15-EC1054AX"],
    hp: ["HP PAVILION 15-EC1054AX"],
    microsoft: ["HP PAVILION 15-EC1054AX"],
    samsung: ["HP PAVILION 15-EC1054AX"],
    sony: ["HP PAVILION 15-EC1054AX"],
    toshiba: ["HP PAVILION 15-EC1054AX"],
    xiaomi: ["HP PAVILION 15-EC1054AX"],
  },
};

export const deviceType = ["Smartphone", "Laptop"];
