export const model = {
  Smartphone: [
    "Apple",
    "Asus",
    "Google",
    "Huawei Honor",
    "LG",
    "Motorola",
    "Nothing Phone (1)",
    "OnePlus",
    "Oppo",
    "Poco",
    "Realme",
    "Samsung",
    "Vivo",
    "Xiaomi Redmi",
    "iQOO",
    "Nokia",
    "Blackberry",
    "10. or G",
    "Infinix",
    "Lenovo",
    "LG",
    "Micromax",
    "Tecno",
  ],
  Laptop: [
    "Apple Macbook",
    "Microsoft Surface",
    "Dell Alienware",
    "Asus",
    "MSI Laptops",
    "Razer Laptops",
    "MI Laptops",
    "Lenovo Laptops",
    "HP Laptops",
  ],
  Charger: [
    "Apple",
    "OnePlus",
    "Realme",
    "Oppo",
    "Redmi",
    "Samsung",
    "IQOO",
    "Vivo",
    "Xiaomi",
    "Nothing Phone",
    "Nokia",
    "Huawei",
  ],
  // card: [
  //   "Debit Card\n",
  //   "Rectangle Chip\n",
  //   "Square Chip\n",
  //   "Credit Card\n",
  //   "Rectangle Chip\n",
  //   "Square Chip\n",
  //   "Metro Card\n",
  // ],
};

export const versionname = {
  Smartphone: {
    apple: [
      "Apple iPhone 14",
      "Apple iPhone 14 Pro ",
      "Apple iPhone 14 Pro Max ",
      "Apple iPhone 14 Plus",
      "Apple iPhone 13 ",
      "Apple iPhone 13 Pro",
      "Apple iPhone 13 Pro Max",
      "Apple iPhone 13 Mini",
      "Apple iPhone 12",
      "Apple iPhone 12 Mini",
      "Apple iPhone 12 Pro ",
      "Apple iPhone 12 Pro Max",
      "Apple iPhone 11",
      "Apple iPhone 11 Pro ",
      "Apple iPhone 11 Pro Max",
      "Apple iPhone XS",
      "Apple iPhone XS Max ",
      "Apple iPhone X ",
      "Apple iPhone XR ",
      "Apple iPhone SE 2020",
      "Apple iPhone 8",
      "Apple iPhone 8 Plus ",
      "Apple iPhone 7",
      "Apple iPhone 7 Plus ",
      "Apple iPhone 6 ",
      "Apple iPhone 6 Plus ",
      "Apple iPhone 6S ",
      "Apple iPhone 6S Plus ",
      "Apple iPhone 5",
      "Apple iPhone 5C ",
      "Apple iPhone 5S",
      "Apple iPhone SE",
    ],
    asus: [
      "Asus Rog 2",
      "Asus Rog 3",
      "Asus Rog 5",
      "Asus Zenfone Max Pro M1 ",
      "Asus Zenfone Max Pro M2 ",
      "Asus Zenfone Max M2 (No Sides)",
      "Asus Zenfone 5Z",
      "Asus Zenfone 6",
      "Asus Zenfone 6Z",
      "Asus Zenfone 8Z (No Sides)",
    ],
    google: [
      "Google Pixel 2",
      "Google Pixel 2 Xl ",
      "Google Pixel 3 ",
      "Google Pixel 3A ",
      "Google Pixel 3Xl",
      "Google Pixel 3A XL",
      "Google Pixel 4",
      "Google Pixel 4Xl",
      "Google Pixel 4A",
      "Google Pixel 4A 5G",
      "Google Pixel 5",
      "Google Pixel 5A",
      "Google Pixel 6",
      "Google Pixel 6A",
      "Google Pixel 6 Pro",
      "Google Pixel 7 (No Sides)",
      "Google Pixel 7 Pro (No Sides)",
    ],
    nokia: [
      "Nokia 1",
      "Nokia 2",
      "Nokia 2.1 (2018)",
      "Nokia 3",
      "Nokia 3.1",
      "Nokia 3.2",
      "Nokia 4",
      "Nokia 4.2",
      "Nokia 5",
      "Nokia 5.1 Plus(2018)",
      "Nokia 5.3",
      "Nokia 6 (2017)",
      "Nokia 6.1 (2018) ",
      "Nokia 6.1 Plus (2018)",
      "Nokia 6.2 (No Sides)",
      "Nokia 7 Plus",
      "Nokia 7.1",
      "Nokia 7.2",
      "Nokia 8",
      "Nokia 8.1",
      "Nokia 9",
      "Nokia C3",
      "Nokia G20 (No Sides)",
      "Nokia G21 (No Sides)",
    ],
    "huawei honor": [
      "Huawei Honor 10",
      "Huawei Honor 10X Lite",
      "Huawei Honor 10 Lite",
      "Huawei Honor 20",
      "Huawei Honor 20 Pro",
      "Huawei Honor 20S",
      "Huawei Honor 20i",
      "Huawei Honor 30",
      "Huawei Honor 3C",
      "Huawei Honor 4C",
      "Huawei Honor 4X",
      "Huawei Honor 5A",
      "Huawei Honor 5C",
      "Huawei Honor 5X",
      "Huawei Honor 6",
      "Huawei Honor 6 Plus",
      "Huawei Honor 6X",
      "Huawei Honor 7A",
      "Huawei Honor 7C",
      "Huawei Honor 7X",
      "Huawei Honor 7i",
      "Huawei Honor 8",
      "Huawei Honor 8 Lite",
      "Huawei Honor 8 Pro",
      "Huawei Honor 8C",
      "Huawei Honor 8X",
      "Huawei Honor 8A 2020",
      "Huawei Honor 8A Pro",
      "Huawei Honor 8A Prime",
      "Huawei Honor 9 Lite",
      "Huawei Honor 9I",
      "Huawei Honor 9N",
      "Huawei Honor 9X",
      "Huawei Honor 9X Pro",
      "Huawei Honor 9X Lite",
      "Huawei Honor Holly 2",
      "Huawei Honor P Lite",
      "Huawei Honor P8 Lite",
      "Huawei Honor P9",
      "Huawei Honor P9 Plus",
      "Huawei Honor P9 Lite",
      "Huawei Honor P10",
      "Huawei Honor P10 Lite",
      "Huawei Honor P10 Plus",
      "Huawei Honor P20",
      "Huawei Honor P20 Lite",
      "Huawei Honor P20 Pro",
      "Huawei Honor P30",
      "Huawei Honor P30 Pro",
      "Huawei Honor P30 Lite",
      "Huawei Honor P40",
      "Huawei Honor P40 Pro",
      "Huawei Honor P40 Pro Plus (No Sides)",
      "Huawei Honor P50",
      "Huawei Honor P50 Pro",
      "Huawei Honor P6",
      "Huawei Honor P7",
      "Huawei Honor P8",
      "Huawei Honor Play",
      "Huawei Honor V10",
      "Huawei Honor V20",
      "Huawei Honor Y7 Prime 2019",
      "Huawei Honor Y6 Prime 2019",
      "Huawei Honor Y9 2019",
      "Huawei Honor Y9 Prime 2019",
      "Huawei Honor Nova 3i",
      "Huawei Honor Nova 6 SE",
      "Huawei Honor Nova Y9A",
      "Huawei Honor Nova 8 SE",
      "Huawei Honor Nova 9",
      "Huawei Honor Nova 9 Pro",
      "Huawei Honor 7 5G",
      "Huawei Honor Mate 20",
      "Huawei Honor Mate 20 Lite",
      "Huawei Honor Mate 20 Pro",
      "Huawei Honor Mate 30 Lite",
      "Huawei Honor Mate 30  Pro",
      "Huawei Honor Mate 30 5G",
      "Huawei Honor Mate 40 Pro",
      "Huawei Honor 50",
      "Huawei Honor 50 Lite",
    ],
    motorola: ["LG G8X ThinQ", "LG Wign"],
    "nothing phone (1)": ["Nothing Phone (1)"],
    oneplus: [
      "OnePlus 5",
      "OnePlus 5T",
      "OnePlus 6",
      "OnePlus 6T",
      "OnePlus 7",
      "OnePlus 7T",
      "OnePlus 7 Pro",
      "OnePlus Nord",
      "OnePlus Nord 2",
      "OnePlus 8T",
      "OnePlus 8",
      "OnePlus 8 Pro",
      "OnePlus X",
      "OnePlus 9",
      "OnePlus 9 Pro",
      "OnePlus 9R",
      "OnePlus 9RT 5G",
      "OnePlus Nord CE 2 5G",
      "OnePlus Nord CE 5G ",
      "OnePlus Nord CE 2 LITE ",
      "OnePlus Nord N200",
      "OnePlus Nord N10",
      "OnePlus Nord 2T 5G ",
      "OnePlus 10 pro (5G)",
      "OnePlus Nord N20 SE ",
      "OnePlus 10R (5G) ",
      "OnePlus 10T",
    ],
    oppo: [
      "Oppo A3",
      "Oppo A3S",
      "Oppo A5",
      "Oppo A5S",
      "Oppo A5 2020",
      "Oppo A7",
      "Oppo A9",
      "Oppo A9 2020",
      "Oppo A12",
      "Oppo A15s",
      "Oppo A16E",
      "Oppo A16K ",
      "Oppo A17K",
      "Oppo A31",
      "Oppo A33",
      "Oppo A37",
      "Oppo A37F",
      "Oppo A39",
      "Oppo A51",
      "Oppo A52",
      "Oppo A53",
      "Oppo A53s 4G",
      "Oppo A54 ",
      "Oppo A57",
      "Oppo A71",
      "Oppo A74 5G",
      "Oppo A75",
      "Oppo A76",
      "Oppo A77 4G",
      "Oppo A79",
      "Oppo A83",
      "Oppo A95 5G",
      "Oppo A96",
      "Oppo F1",
      "Oppo F1S",
      "Oppo F1 Plus",
      "Oppo F3",
      "Oppo F3 Plus",
      "Oppo F5",
      "Oppo F5 Youth",
      "Oppo F7",
      "Oppo F9",
      "Oppo F9 Pro",
      "Oppo F9 Pro Plus",
      "Oppo F11",
      "Oppo F15",
      "Oppo F17",
      "Oppo F17 Pro",
      "Oppo F19",
      "Oppo F19 Pro",
      "Oppo F19 Pro Plus",
      "Oppo F19S ",
      "Oppo F21 Pro (4G)",
      "Oppo F21 Pro (5G)",
      "Oppo F21S Pro (5G)",
      "Oppo Find N",
      "Oppo Find X",
      "Oppo Find X2",
      "Oppo K1",
      "Oppo K9 5G",
      "Oppo K9S",
      "Oppo K9 Pro 5G",
      "Oppo K10",
      "Oppo K3",
      "Oppo Neo 5",
      "Oppo Neo 7",
      "Oppo R7",
      "Oppo R9",
      " Oppo R11",
      "Oppo R11S",
      "Oppo R15",
      "Oppo R15 Pro",
      "Oppo R17 Pro",
      "Oppo Reno",
      "Oppo Reno 2",
      "Oppo Reno 2f",
      "Oppo Reno 2Z",
      "Oppo Reno 3 Pro",
      "Oppo Reno 4",
      "Oppo Reno 4 Pro",
      "Oppo Reno 5 5G",
      "Oppo Reno 5 Pro",
      "Oppo Reno 5Z",
      "Oppo Reno 6",
      "Oppo Reno 6 Pro 5G",
      "Oppo Reno 7 ",
      "Oppo Reno 7 Pro 5G",
      "Oppo Reno 10X Zoom",
      "Oppo Reno 8 5G",
      "Oppo Reno 8 Pro 5G",
      "Oppo A1K",
    ],
    poco: [
      "Poco F1",
      "Poco F2 Pro",
      "Poco F3",
      "Poco F3 GT 5G ",
      "Poco F4 ",
      "Poco F4 GT",
      "Poco X2",
      "Poco X3",
      "Poco X3 NFC",
      "Poco X3 GT ",
      "Poco X3 Pro",
      "Poco X4 Pro (No Sides)",
      "Poco M2",
      "Poco M2 Pro",
      "Poco C3",
      "Poco M3 (No Sides)",
      "Poco C31",
      "Poco M3 Pro 5G",
      "Poco M4 5G (No Sides) ",
      "Poco M4 Pro 5G",
    ],
    realme: [
      "Realme 1",
      "Realme 2",
      "Realme 2 Pro",
      "Realme 3",
      "Realme 3 Pro",
      "Realme 3i",
      "Realme 5",
      "Realme 5i",
      "Realme 5s",
      "Realme 6",
      "Realme 6 Pro",
      "Realme 6i",
      "Realme 7",
      "Realme 7 Pro",
      "Realme 7i",
      "Realme 8",
      "Realme 8 5G",
      "Realme 8 Pro",
      "Realme 8i",
      "Realme 8s",
      "Realme 9i",
      "Realme 9 4G",
      "Realme 9 5G",
      "Realme 9 SE",
      "Realme 9 Pro 5G",
      "Realme 9 Pro Plus 5G",
      "Realme 10 Pro 5G",
      "Realme 10 Pro Plus 5G",
      "Realme C1",
      "Realme C2",
      "Realme C3",
      "Realme C11",
      "Realme C12",
      "Realme C15",
      "Realme C17",
      "Realme C20",
      "Realme C21",
      "Realme C21Y",
      "Realme C25",
      "Realme C25Y",
      "Realme C31",
      "Realme C33",
      "Realme C35",
      "Realme Narzo 10",
      "Realme Narzo 10A",
      "Realme Narzo 20",
      "Realme Narzo 20A",
      "Realme Narzo 20 Pro",
      "Realme Narzo 20A",
      "Realme Narzo 30",
      "Realme Narzo 30 4G",
      "Realme Narzo 30 5G",
      "Realme Narzo 30 Pro 5G",
      "Realme Narzo 30A ",
      "Realme Narzo 50",
      "Realme Narzo 50i",
      "Realme Narzo 50A",
      "Realme Narzo 50A Prime",
      "Realme Narzo 50 Pro 5G",
      "Realme U1",
      "Realme X",
      "Realme X2",
      "Realme X3",
      "Realme X3 Super Zoom",
      "Realme X50",
      "Realme X50 Pro",
      "Realme X7 ",
      "Realme X7 Pro",
      "Realme X7 Max",
      "Realme XT",
      "Realme GT (5G)",
      "Realme GT Master Edition(5G)",
      "Realme GT 2",
      "Realme GT Neo 2",
      "Realme GT 2 Pro",
      "Realme GT Neo 3",
      "Realme GT Neo 3T 5G",
    ],
    lenovo: [
      "Lenovo K3 Note",
      "Lenovo K4 Note ",
      "Lenovo K5 Note ",
      "Lenovo K6 Note",
      "Lenovo K6 Power",
      "Lenovo K8 ",
      "Lenovo K8 Note",
      "Lenovo K8 Plus",
      "Lenovo Vibe K6 Power",
      "Lenovo Vibe P1",
      "Lenovo Zuk Z1 ",
      "Lenovo Zuk Z2",
      "Lenovo Zuk Z2 Lite",
      "Lenovo Zuk Z2 Plus",
      "Lenovo Zuk Z2 Pro",
    ],
    lg: [
      "Lg G5",
      "Lg G6",
      "Lg G7",
      "Lg G7,",
      "Lg G8X Thinq",
      "Lg K10",
      "Lg K10 2017",
      "Lg K7",
      "Lg K9",
      "Lg K90",
      "Lg Pro Lite",
      "Lg Q6",
      "Lg Q7",
      "Lg Q8",
      "Lg Stylus 2",
      "Lg Stylus 4",
      "Lg V20",
      "Lg V30",
      "Lg V30,",
      "Lg V40 Thinq",
      "Lg Velvet",
      "Lg W30",
      "Lg X Power",
      "Lg Wing",
      "Lg Q Stylus Plus",
    ],
    samsung: [
      "Samsung Galaxy A03 Core ",
      "Samsung Galaxy A04S ",
      "Samsung Galaxy A6 Plus 2018",
      "Samsung Galaxy A8 Plus ",
      "Samsung Galaxy A8 Star",
      "Samsung Galaxy A9 ",
      "Samsung Galaxy A9 2016",
      "Samsung Galaxy A9 2018",
      "Samsung Galaxy A9 Pro",
      "Samsung Galaxy A10",
      "Samsung Galaxy A10S",
      "Samsung Galaxy A12",
      "Samsung Galaxy A20E (No Sides)",
      "Samsung Galaxy A20",
      "Samsung Galaxy A21 (No Sides)",
      "Samsung Galaxy A20S",
      "Samsung Galaxy A33 (5G)",
      "Samsung Galaxy A30",
      "Samsung Galaxy A31",
      "Samsung Galaxy A32",
      "Samsung Galaxy A30s",
      "Samsung Galaxy A21S",
      "Samsung Galaxy A22 ",
      "Samsung Galaxy A33 ",
      "Samsung Galaxy A22 5G",
      "Samsung Galaxy A23",
      "Samsung Galaxy A13 5G ",
      "Samsung Galaxy A42",
      "Samsung Galaxy A41",
      "Samsung Galaxy A50S",
      "Samsung Galaxy A50",
      "Samsung Galaxy A50S",
      "Samsung Galaxy A51 ",
      "Samsung Galaxy A52",
      "Samsung Galaxy A52s 5G",
      "Samsung Galaxy A53 5G",
      "Samsung Galaxy A60 ",
      "Samsung Galaxy A70 ",
      "Samsung Galaxy A70S ",
      "Samsung Galaxy A71 ",
      "Samsung Galaxy A72",
      "Samsung Galaxy A73",
      "Samsung Galaxy A80",
      "Samsung Galaxy Alpha",
      "Samsung Galaxy C7 ",
      "Samsung Galaxy C7 Pro",
      "Samsung Galaxy C9",
      "Samsung Galaxy C9 Pro ",
      "Samsung Galaxy Core 2",
      "Samsung Galaxy E5",
      "Samsung Galaxy E7 ",
      "Samsung Galaxy F12",
      "Samsung Galaxy F22 (No Sides)",
      "Samsung Galaxy F23",
      "Samsung Galaxy F41 ",
      "Samsung Galaxy F42 5G",
      "Samsung Galaxy F62",
      "Samsung Galaxy J7 Next",
      "Samsung Galaxy J7 Prime",
      "Samsung Galaxy J7 Pro",
      "Samsung Galaxy J8 2018",
      "Samsung Galaxy M02",
      "Samsung Galaxy M02S",
      "Samsung Galaxy M10",
      "Samsung Galaxy M11",
      "Samsung Galaxy M12",
      "Samsung Galaxy M13 5G",
      "Samsung Galaxy M20",
      "Samsung Galaxy M21",
      "Samsung Galaxy M21 2021",
      "Samsung Galaxy M22 (No Sides)",
      "Samsung Galaxy M30",
      "Samsung Galaxy M30s",
      "Samsung Galaxy M31",
      "Samsung Galaxy M32",
      "Samsung Galaxy M32 5G",
      "Samsung Galaxy M33 5G",
      "Samsung Galaxy M40",
      "Samsung Galaxy M42",
      "Samsung Galaxy M51",
      "Samsung Galaxy M52 5G",
      "Samsung Galaxy M53 5G",
      "Samsung Galaxy M62 ",
      "Samsung Galaxy Note 9",
      "Samsung Galaxy Note 9 Pro",
      "Samsung Galaxy Note Edge",
      "Samsung Galaxy Note 10 ",
      "Samsung Galaxy Note 10 Lite",
      "Samsung Galaxy Note 10 Plus",
      "Samsung Galaxy Note 20",
      "Samsung Galaxy Note 20 Ultra ",
      "Samsung Galaxy On 6 ",
      "Samsung Galaxy On 8",
      "Samsung Galaxy On Max",
      "Samsung Galaxy On Next",
      "Samsung Galaxy S10 ",
      "Samsung Galaxy S10 Lite ",
      "Samsung Galaxy S10 Plus",
      "Samsung Galaxy S10E",
      "Samsung Galaxy S20",
      "Samsung Galaxy S20 FE",
      "Samsung Galaxy S20 Plus",
      "Samsung Galaxy S20 Ultra",
      "Samsung Galaxy S21",
      "Samsung Galaxy S21 Plus",
      "Samsung Galaxy S21 Ultra ",
      "Samsung Galaxy S21 FE 5G",
      "Samsung Galaxy S22",
      "Samsung Galaxy S22 Plus ",
      "Samsung Galaxy S22 Ultra",
      "Samsung Galaxy Z2",
      "Samsung Galaxy Z3",
      "Samsung Galaxy Z Flip",
      "Samsung Galaxy Z Flip 3",
      "Samsung Galaxy Z Flip 4 ",
      "Samsung Galaxy Fold",
      "Samsung Galaxy Z Fold 2",
      "Samsung Galaxy Z Fold 3",
      "Samsung Galaxy Z Fold 4",
    ],
    infinix: [
      "Infinix 10 Play",
      "Infinix Hot 10 (No Sides)",
      "Infinix Hot 10S ",
      "Infinix Hot 11",
      "Infinix Hot 11S",
      "Infinix Hot 4",
      "Infinix Hot 4 Pro",
      "Infinix Hot 6 (No Sides)",
      "Infinix Hot 7 (No Sides)",
      "Infinix Hot 8 (No Sides)",
      "Infinix Hot 9 (No Sides)",
      "Infinix Hot 9 Pro ",
      "Infinix Hot 9 Pro (No Sides)",
      "Infinix Note 10",
      "Infinix Note 11S",
      "Infinix Note 12",
      "Infinix Note 4 Pro",
      "Infinix Note 5",
      "Infinix Note 7",
      "Infinix Note 8",
      "Infinix Note 9",
      "Infinix Smart 5A ",
      "Infinix Zero 8i (No Sides)",
    ],
    vivo: [
      "Vivo Nex A",
      "Vivo Nex S",
      "Vivo S1",
      "Vivo S1 Pro",
      "Vivo U10 ",
      "Vivo U20",
      "Vivo V1 Max",
      "Vivo V3",
      "Vivo V3 Max",
      "Vivo V5",
      "Vivo V5 Plus ",
      "Vivo V5S",
      "Vivo V6",
      "Vivo V7",
      "Vivo V7 Plus",
      "Vivo V9",
      "Vivo V9 Youth",
      "Vivo V11",
      "Vivo V11 Pro",
      "Vivo V12G",
      "Vivo V15",
      "Vivo V15 Pro",
      "Vivo V17",
      "Vivo V17 Pro",
      "Vivo V19",
      "Vivo V20",
      "Vivo V20 Pro ",
      "Vivo V20 SE",
      "Vivo V21",
      "Vivo V21E 4G",
      "Vivo V23 5G",
      "Vivo V23 Pro 5G",
      "Vivo V23E 5G",
      "Vivo V25 Pro",
      "Vivo V25 5G",
      "Vivo X20",
      "Vivo X20 Plus",
      "Vivo X3S",
      "Vivo X5 Max",
      "Vivo X5 Pro",
      "Vivo X50",
      "Vivo X50 Pro",
      "Vivo X6",
      "Vivo X7",
      "Vivo X7L",
      "Vivo X60",
      "Vivo X60 Pro",
      "Vivo X60 Pro Plus",
      "Vivo X70 Pro",
      "Vivo X70 Pro Plus",
      "Vivo X80",
      "Vivo X80 Pro",
      "Vivo Y02",
      "Vivo Y3s",
      "Vivo Y11",
      "Vivo Y12",
      "Vivo Y12S",
      "Vivo Y15 2019",
      "Vivo Y15S",
      "Vivo Y15C",
      "Vivo Y17",
      "Vivo Y19",
      "Vivo Y20",
      "Vivo Y20A",
      "Vivo Y20i",
      "Vivo Y20G 2021",
      "Vivo Y20T",
      "Vivo Y21",
      "Vivo Y21T",
      "Vivo Y21S 2020",
      "Vivo Y21S 2021",
      "Vivo Y21E",
      "Vivo Y21G",
      "Vivo Y22 (2022)",
      "Vivo Y27",
      "Vivo Y27L",
      "Vivo Y28",
      "Vivo Y30",
      "Vivo Y31",
      "Vivo Y33S",
      "Vivo Y33T",
      "Vivo Y35 (2022)",
      "Vivo Y50 ",
      "Vivo Y51",
      "Vivo Y51A",
      "Vivo Y53",
      "Vivo Y53S",
      "Vivo Y55L",
      "Vivo Y55 S",
      "Vivo Y66",
      "Vivo Y69",
      "Vivo Y71",
      "Vivo Y71l",
      "Vivo Y72 5G",
      "Vivo Y73",
      "Vivo Y75 5G",
      "Vivo Y81",
      "Vivo Y83",
      "Vivo Y83 Pro",
      "Vivo Y91",
      "Vivo Y91i",
      "Vivo Y93",
      "Vivo Y95",
      "Vivo Z1 Pro",
      "Vivo Z10",
    ],
    "xiaomi redmi": [
      "Xiaomi Mi 3",
      "Xiaomi Mi 4",
      "Xiaomi Mi 4S",
      "Xiaomi Mi 5",
      "Xiaomi Mi 6",
      "Xiaomi Mi 9",
      "Xiaomi Mi 10",
      "Xiaomi Mi 10i",
      "Xiaomi Mi 10T 5G",
      "Xiaomi Mi 10T Lite",
      "Xiaomi Mi 11X",
      "Xiaomi Mi 11X Pro",
      "Xiaomi Mi 11 Lite ",
      "Xiaomi Mi 11 Lite NE",
      "Xiaomi Mi 11 Ultra",
      "Xiaomi Mi 11T Pro",
      "Xiaomi Mi A3",
      "Xiaomi Redmi 2S",
      "Xiaomi Redmi 3S",
      "Xiaomi Redmi 3S PLus",
      "Xiaomi Redmi 3S Prime",
      "Xiaomi Redmi 4",
      "Xiaomi Redmi 4A",
      "Xiaomi Redmi 4X",
      "Xiaomi Redmi 5",
      "Xiaomi Redmi 5 PLus",
      "Xiaomi Redmi 5A",
      "Xiaomi Redmi 6",
      "Xiaomi Redmi 7",
      "Xiaomi Redmi 7A",
      "Xiaomi Redmi 8",
      "Xiaomi Redmi 8A",
      "Xiaomi Redmi 8A Dual",
      "Xiaomi Redmi 9",
      "Xiaomi Redmi 9 Power",
      "Xiaomi Redmi 9 Prime",
      "Xiaomi Redmi 9 Active",
      "Xiaomi Redmi 9A (No Sides)",
      "Xiaomi Redmi 9i Sport",
      "Xiaomi Redmi 10A",
      "Xiaomi Redmi 10C",
      "Xiaomi Redmi 10 Power",
      "Xiaomi Redmi 11i 5G",
      "Xiaomi Redmi 11i HyperCharge",
      "Xiaomi Redmi K20",
      "Xiaomi Redmi K20 Pro",
      "Xiaomi Redmi A1",
      "Xiaomi Redmi A2",
      "Xiaomi Redmi A2 Lite",
      "Xiaomi Redmi Mi Max",
      "Xiaomi Redmi Mi Max 2",
      "Xiaomi Redmi Mi Mix 2",
      "Xiaomi Redmi Note Prime",
      "Xiaomi Redmi Note 2",
      "Xiaomi Redmi Note 3",
      "Xiaomi Redmi Note 4",
      "Xiaomi Redmi Note 5",
      "Xiaomi Redmi Note 5 Pro",
      "Xiaomi Redmi Note 6 Pro",
      "Xiaomi Redmi Note 7",
      "Xiaomi Redmi Note 7 Pro",
      "Xiaomi Redmi Note 7S",
      "Xiaomi Redmi Note 8",
      "Xiaomi Redmi Note 8 Pro",
      "Xiaomi Redmi Note 9 ",
      "Xiaomi Redmi Note 9 Pro",
      "Xiaomi Redmi Note 9 Pro Max",
      "Xiaomi Redmi Note 9S",
      "Xiaomi Redmi Note 9T ",
      "Xiaomi Redmi Note 9T 5G (No Sides) ",
      "Xiaomi Redmi Note 10",
      "Xiaomi Redmi Note 10S",
      "Xiaomi Redmi Note 10 Pro",
      "Xiaomi Redmi Note 10 Pro Max",
      "Xiaomi Redmi Note 10T 5G",
      "Xiaomi Redmi 10 Prime",
      "Xiaomi Redmi 11 Prime 5G",
      "Xiaomi Redmi 11T 5G",
      "Xiaomi Redmi Note 11",
      "Xiaomi Redmi Note 11 Pro",
      "Xiaomi Redmi Note 11 pro plus (5G )",
      "Xiaomi Redmi Note 11S",
      "Xiaomi Redmi 12 pro (5G)",
      "Xiaomi Redmi Y1",
      "Xiaomi Redmi Y1 Lite",
      "Xiaomi Redmi Y2",
      "Xiaomi Redmi Y3",
      "Xiaomi Black Shark 2",
      "Xiaomi Redmi K50i (5G)",
      "Xiaomi 12s Ultra",
      "Xiaomi 12s Lite",
    ],
    iqoo: [
      "Vivo IQOO 3 (No Sides)",
      "Vivo IQOO Neo 3 (No Sides)",
      "Vivo IQOO Neo 6 (5G)",
      "Vivo IQOO Z3",
      "Vivo IQOO 7",
      "Vivo IQOO Z1X",
      "Vivo IQOO 7 Legend (No Sides)",
      "Vivo IQOO Z5",
      "Vivo IQOO Z6 5G",
      "Vivo IQOO Z6 Pro 5G",
      "Vivo IQOO Z6 (44W)",
      "Vivo IQOO Z6 Lite 5G",
      "Vivo IQOO 9 5G",
      "Vivo IQOO 9 SE 5G",
      "Vivo IQOO 9 Pro 5G",
      "Vivo IQOO 9T (No Sides)",
    ],
    "10. or g": ["10. or G (No Sides) ", "10. or G 2"],
    blackberry: ["Blackberry Passport", "Blackberry Priv", "Blackberry Z10"],
  },
  Laptop: {
    "apple macbook": [
      "Macbook Air 11 inch (2010)				",
      "Macbook Air 11 inch (2013)				",
      "Macbook Air 13.3 inch (2010-2017)				",
      "Macbook Air 13.3 inch (2018 -2020)				",
      "MacBook Air 13 M2 2022				",
      "MacBook 12-inch A1534				",
      "Macbook M1 2020 Air				",
      "MacBook Pro 13 inch (2009, 2010, 2011, 2012) A1278				",
      "MacBook Pro 13 inch (2012, 2013, 2014, 2015) A1425, A1502				",
      "MacBook Pro 13 inch (2016, 2017) A1706, A1708				",
      "MacBook Pro 13 inch (2020 &amp; M1) A2289, A2251, A2338				",
      "MacBook Pro 14 inch (2021) A2442				",
      "MacBook Pro 15 inch (2008 - 2011) A1286				",
      "MacBook Pro 15 inch (2012 - 2015) A1398				",
      "MacBook Pro 15 inch (2016 - 2019) A1707, A1990				",
      "MacBook Pro 16 inch (2019) A2141				",
      "MacBook Pro 16 inch (2021) A2485				",
      "MacBook Pro 13 M2 2022				",
    ],
    "microsoft surface": [
      "Surface 1/Pro 1 (2012)				",
      "Surface 2/Pro 2 (2013)				",
      "Surface 3 (10.8-inch, 2015)				",
      "Surface Pro 3 (2014)				",
      "Surface Pro 4 (2015)				",
      "Surface Pro 5 (2017)				",
      "Surface Pro 6 (2018)				",
      "Surface Pro 7 (2019)				",
      "Surface Pro X (2019)				",
      "Surface Book 13.5 inch (2016)				",
      "Surface Book 2 15 inch (2017)				",
      "Type Cover for Surface Pro 4/5/6/7				",
      "Type Cover for Surface 3				",
      "Surface Pro 8 (2021)				",
      "Surface Book 3				",
      "Surface Laptop 4				",
      "Suface Laptop 1, 2 – 1769				",
      "Surface Book 1 (2015)				",
      "Surface Book 2 – 13 inch (2017)				",
      "Surface Go (2018) (Model 1824)				",
      "Surface Go 2 (2020 – Model 1901)				",
      "Surface 3 Tablet (1657)				",
      "Surface Laptop 3 (13.5 inch) (2019, Model 1868)				",
      "Surface Laptop 3 (15″)				",
      "Surface Laptop Go (2020, Model 1943)				",
      "Surface Laptop Studio				",
    ],
    "dell alienware": [
      "Dell Alienware 15 R2 (P42F)				",
      "Dell Alienware 17 R4 (P31E)				",
      "Dell Alienware 15 R3 (P69F)				",
      "Dell Alienware 17R4-7700 P31F				",
      "Dell Alienware M11x R2 (P06T)				",
      "Dell Alienware M14x R1, R2 (P18G)				",
      "Dell Alienware m17 R2 (P41E)				",
      "Dell Alienware M17x R4 (P11E)				",
      "Dell Alienware M15 Ryzen Edition R5 (P109F)				",
    ],
    asus: [
      "ASUS ROG Strix G15 G512				",
      "ASUS ROG Strix G531GT				",
      "Asus Vivibook A512 (F512, X512, K512, S512) Series				",
      "Asus TUF Gaming A15 FA506				",
      "Asus A42				",
      "Asus A556, X556, U556				",
      "Asus A456				",
      "Asus E200				",
      "Asus E402				",
      "Asus FX503				",
      "Asus K43, X43, X44				",
      "Asus K52				",
      "Asus K53				",
      "Asus K55, A55				",
      "Asus K501				",
      "Asus ROG GL551J				",
      "Asus ROG GL552J				",
      "Asus ROG Strix GL503				",
      "Asus ROG Strix GL553				",
      "Asus ROG Strix GL703				",
      "Asus S410, A410				",
      "Asus Transformer Book Flip TP300L				",
      "Asus Transformer Book Flip TP550				",
      "Asus VivoBook 15 A512				",
      "Asus VivoBook S14 A411				",
      "Asus Vivobook X530				",
      "Asus Vivobook X542U				",
      "Asus X8AIJ				",
      "Asus X45C				",
      "Asus X453				",
      "Asus X540, A540				",
      "Asus ZenBook Flip UX360U				",
      "Asus Zenbook UX410				",
      "Asus Zenbook UX430				",
      "Asus X454, F454 Series 				",
      "Asus X541, A541 Series				",
      "Asus ZenBook Flip UX360C				",
      "Asus ZenBook Flip UX360 Series				",
      "Asus K450, P450 Series				",
      "Asus ROG Gaming G73 Series				",
      "Asus Vivobook A412 Series				",
      "Asus Vivobook A510, S510, X510 Series				",
      "Asus X550, P550, A550, F550 Series				",
      "Asus X554, X555, F554, F555, K, A, P Series				",
      "Asus TUF Gaming FX504				",
      "Asus ROG STrix Q733Q				",
      "Asus ROG Zephyrus G15 GA502				",
    ],
    "msi laptops": [
      "MSI Bravo 15 A4DCR				",
      "MSI 15M A11SDK				",
      "MSI GL73				",
      "MSI GL75 Leopard 10SDR				",
      "MSI GP72M 7REX				",
      "MSI GS63RV				",
      "MSI GS65 8RF				",
      "MSI GS73				",
      "MSI GT62RV - 7RE				",
      "MSI GV72- 7RD				",
      "MSI MS - 16GH				",
      "MSI MS - 16J7				",
      "MSI MS - 16P3				",
      "MSI MS-175A				",
      "MSI MS1763 GT70				",
      "MSI Prestige 15 A10SC				",
      "MSI GL75 Leopard 10SDR				",
      "MSI GF75 Thin 10SC				",
      "MSI 14 B10MW				",
      "MSI 14 B10RASW				",
      "MSI Bravo 15 B5DD				",
      "MSI GE60 MS-16GF				",
      "MSI GF63 Thin 9SC (MS-16R3), Thin 10SC (MS-16R4), Bravo 15				",
      "MSI GF75 Thin 95C, Bravo 17 A4DDR 200VN				",
      "MSI GL62m, GP62 7 RD, GV62, CX62 (16j9)				",
      "MSI GL63 8RD				",
      "MSI GL65 95DK (MS-16U5), Alpha 15 (MS-16U6)				",
      "MSI GP62 7RD, 7RDX				",
      "MSI GP63, GL63 (MS-16P6)				",
      "MSI GS65 Series				",
      "MSI GS66 Stealth Series				",
      "MSI GT70 2PC DOMINATOR				",
      "MSI Prestige PE60 (MS-16J5) Series				",
      "MSI GF63 8RC Series				",
      "MSI GP60 2PE LEOPARD				",
      "MSI Moderm 14 A10 (MS-14B) Series				",
      "MSI Moderm 15 A10 (MS-1551) Series				",
      "MSI 14 B11M				",
      "MSI BRAVO 15 A4DCR				",
      "MSI CX62 7QL				",
      "MSI GE60 2PC				",
      "MSI GE62 6QD APACHE PRO				",
      "MSI GE73 7RC, 7RD				",
      "MSI GF62-7RE				",
      "MSI GL62 6QD				",
      "MSI GP63 LEOPARD 8RD, 8RE				",
      "MSI GP72M 7REX Leopard Pro				",
      "MSI GS63VR 7RG Stealth Pro				",
      "MSI 15 A10M				",
      "MSI 14 B11 Series				",
      "MSI GF65 Series				",
      "MSI Katana GF66				",
      "MSI MS GS63VR (16K3)				",
      "MSI Prestige 14 A10RP				",
      "MSI Katana GF76 11UC-096VN				",
      "MSI GX63VR (MS-17C3)				",
      "MSI GE63 7RD RAIDER				",
      "MSI 15 A11M (MS-1552)				",
    ],
    "razerl aptops": [
      "Razer Blade 15 RZ09-0270				",
      "Razer Blade Stealth 13 RZ09-03100EM1				",
      "Razer Blade Stealth 1306				",
    ],
    "mi laptops": ["Mi NoteBook 14 (2020)", "Mi NoteBook Ultra"],
    "lenovo laptops": [
      "Lenovo Legion Y530-151CH				",
      "Lenovo LEGION 5 - 15ARH05				",
      "Lenovo LEGION 5 - 15IMH05				",
      "Lenovo Legion Y520				",
      "Lenovo Legion Y530				",
      "Lenovo Legion Y540				",
      "Lenovo Legion Y7000P				",
      "Lenovo Legion Y530, Y540, Y7000				",
      "Lenovo Legion 5 15ACH6				",
      "Lenovo Legion 5 Pro 16ACH6H				",
      "Lenovo Legion Y730 15ICH				",
    ],
    "hp laptops": [
      "HP Pavilion 14-bs Series				",
      "HP Pavilion 14-ck Series				",
      "HP Pavilion 14-v01 Series				",
      "HP Pavilion 14-al Series				",
      "HP Pavilion 15-ab Series				",
      "HP Pavilion 15-cc Series				",
      "HP Pavilion 15-p Series				",
      "HP Pavilion x360 11-ad Series				",
      "HP Pavilion 15-ay Series				",
      "HP Pavilion 15 RT3290				",
      "HP Pavilion 15-cc Series				",
      "HP Pavilion 15-n Series				",
      "HP Pavilion DV4 – 2165dx				",
      "HP Pavilion DV4 – 5220us				",
      "HP Pavilion DV6 – 1126				",
      "HP Pavilion DV6 – 3040us				",
      "HP Pavilion 14-cf Series				",
      "HP Pavilion 14-n Series				",
      "HP Pavilion 15-eg Series				",
      "HP Pavilion G4 2203TX				",
      "HP Pavilion Gaming 15-cx Series				",
      "HP Pavilion Gaming 15-dk Series				",
      "HP Pavilion x360 11-ad Series				",
      "HP Pavilion 14-ce Series				",
      "HP Pavillion X360 14-DH Series				",
      "HP Pavilion 15-cs Series				",
      "HP Pavilion 15-au Series				",
      "HP Pavilion DV2000				",
      "HP Pavilion 14-dv0041TU				",
      "HP Pavilion 14-dv0510TU				",
      "HP Pavilion 15-au010wm				",
      "HP Pavilion 15-ec0050ax, ec1054ax				",
      "HP Pavilion G6 (1323TX)				",
      "HP Pavilion x360 13-u106TU				",
      "HP Pavilion 14-bf018TU				",
      "HP Pavilion 14-A015TU				",
      "HP Pavilion 15-cw1063wm				",
      "HP Pavilion x360 14 – dw0062TU, dw0063TU, dw1016TU (19d54pa)				",
      "HP Pavilion x360 14-dw1018TU				",
    ],
  },
  Charger: {
    apple: [
      "Apple 5W				",
      "Apple 10W 				",
      "Apple 12W				",
      "Apple 18W USB C				",
      "Apple 20W				",
      "Apple 60W Power Adapter (2008)				",
      "Apple 61W USB-C Power Adapter				",
      "Apple 67W USB-C Power Adapter				",
      "Apple 85W Power Adapter 2015				",
      "Apple 85W MagSafe2 Power Adapter 2017				",
      "Apple 87W USB-C Power Adapter				",
      "Apple Magsafe Charger				",
      "Apple Magsafe Battery Pack				",
      "Apple iPad Pro Charger				",
      "Apple Watch Magnetic Charger (2017-18)				",
    ],
    oneplus: [
      "OnePlus Dash (Box Charger) 				\n",
      "OnePlus Warp (Box Charger) USB Type A				\n",
      "OnePlus Warp (65W Charger) USB Type C				\n",
      "OnePlus Warp/SuperVooc (80W Charger)				\n",
    ],
    realme: [
      "Realme Vooc Charger				\n",
      "Realme Flash 10W Charger				\n",
      "Realme Super Vooc 50W 5A				\n",
      "Realme 18W Charger				\n",
    ],
    oppo: [
      "Oppo Fast Charger 30W 5A				\n",
      "Oppo Dash 65W Charger				\n",
      "Oppp Super Vooc 33W				\n",
    ],
    redmi: ["Redmi/Poco Black Charger"],
    samsung: [
      "Samsung F62 Fast Type C				\n",
      "Samsung S8 Charger				\n",
      "Samsung Wireless Charger				\n",
      "Samsung 45W Super Fast Charger				\n",
      "Samsung Travel Adapter 15W				\n",
    ],
    iqoo: ["IQOO Flash Charger 80W"],
    vivo: [
      "Vivo Flash Charger 44W				\n",
      "Vivo Flash Charger 80W				\n",
      "Vivo Flash Charger 2.0 33W				\n",
      "Vivo Universal Charger				\n",
      "Vivo X70 Pro Charger				\n",
    ],
    xiaomi: [
      "Xiaomi Mi 10W Charger				\n",
      "Xiaomi Mi 18W Charger				\n",
      "Xiaomi Mi 22.5W Charger				\n",
      "Xiaomi Mi 27W Charger				\n",
      "Xiaomi Mi 33W Charger				\n",
      "Xiaomi Mi 67W Charger				\n",
    ],
    "nothing phone": ["Nothing Phone (1) Charger"],
    nokia: [" Nokia Ultra Fast Charger 2.4A"],
    huawei: ["              Huawei Charger 2 pin"],
  },
};

export const deviceType = ["Smartphone", "Laptop", "Charger"];
